---
- name: Install newsbeuter
  become: True
  apt:
    name: newsbeuter

- name: Make sure the newsbeuter configuration folder is created
  file:
    path: "{{ home }}/.newsbeuter"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"

- name: Symlink the newsbeuter configuration
  file:
    src: "{{ dotfiles }}/dotfiles/newsbeuter/config"
    dest: "{{ home }}/.newsbeuter/config"
    state: link
    force: True
    owner: "{{ ansible_user }}"

- name: Symlink the newsbeuter URLs
  file:
    src: "{{ dotfiles }}/dotfiles/newsbeuter/urls"
    dest: "{{ home }}/.newsbeuter/urls"
    state: link
    force: True
    owner: "{{ ansible_user }}"
