set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

" git
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive.git'
Plugin 'tpope/vim-git'
Plugin 'sjl/gundo.vim.git'

" text operations
Plugin 'tpope/vim-commentary'
Plugin 'godlygeek/tabular'
Plugin 'Raimondi/delimitMate'
Plugin 'tpope/vim-surround'

" navigation
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'tacahiroy/ctrlp-funky'
Plugin 'tpope/vim-unimpaired'

" motion
Plugin 'Lokaltog/vim-easymotion'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'ervandew/supertab'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-easytags'

"" syntax checker
Plugin 'scrooloose/syntastic'

"" html
Plugin 'mattn/emmet-vim'

"" code completion
Plugin 'Valloric/YouCompleteMe'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'

"" syntax color / colorschemes
Plugin 'chriskempson/tomorrow-theme', {'rtp': 'vim/'}
Plugin 'luochen1990/rainbow'
Plugin 'tomasr/molokai'
Plugin 'altercation/vim-colors-solarized'
Plugin 'gilgigilgil/anderson.vim'

"" python
Plugin 'davidhalter/jedi-vim'
Plugin 'nvie/vim-flake8'
Plugin 'fs111/pydoc.vim'

"" haskell
Plugin 'bitc/vim-hdevtools'

"" elm
Plugin 'lambdatoast/elm.vim'

"" gist
Plugin 'mattn/gist-vim'
Plugin 'mattn/webapi-vim'

" YAML
Plugin 'stephpy/vim-yaml'

" saltstack
Plugin 'saltstack/salt-vim'

" jinja
Plugin 'Glench/Vim-Jinja2-Syntax'

" vagrant
Plugin 'hashivim/vim-vagrant'

call vundle#end()
filetype plugin indent on

" set leader key
let mapleader = ","

" ultisnip mappings
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsListSnippets="<c-k>"

" paste mode
set pastetoggle=<F12>
set t_Co=256
set term=screen-256color
syntax enable
au FileType * setlocal formatoptions-=cro

" getting some better colours with this option
" colorscheme anderson
colorscheme Tomorrow-Night-Eighties
" colorscheme molokai
" colorscheme solarized

" tabular.vim
nmap <Leader>a= :Tabularize /=<CR>
vmap <Leader>a= :Tabularize /=<CR>
nmap <Leader>a: :Tabularize /:zs<CR>
vmap <Leader>a: :Tabularize /:zs<CR>
nmap <Leader>a& :Tabularize /&<CR>
vmap <Leader>a& :Tabularize /&<CR>
nmap <Leader>a:: :Tabularize /:zs<CR>
vmap <Leader>a:: :Tabularize /:zs<CR>
nmap <Leader>a, :Tabularize /,<CR>
vmap <Leader>a, :Tabularize /,<CR>
nmap <Leader>a,, :Tabularize /,zs<CR>
vmap <Leader>a,, :Tabularize /,zs<CR>
nmap <Leader>a<Bar> :Tabularize /<Bar><CR>
vmap <Leader>a<Bar> :Tabularize /<Bar><CR>

" escape parens with Ctrl-e
inoremap <C-e> <C-o>a
inoremap <C-d> <C-o>A
nnoremap <leader>v vib

" strip all whitespace with ,WW
nnoremap <leader>WW :%s/\s\+$//<cr>:let @/=''<CR>

"" auto remove whitespace
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun
" autocmd FileType c,cpp,java,php,ruby,python autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

" source the vimrc file after saving it
if has("autocmd")
  autocmd bufwritepost .vimrc source $MYVIMRC
endif

" edit .vimrc on the fly
noremap <leader>ev <C-w><C-v><C-l>:e $MYVIMRC<cr>

" spell check ',s'
nmap <silent> <leader>s :set spell!<CR>
map <leader>sn ]s
map <leader>sp [s
map <leader>sa zg
map <leader>s? z=

" better tabbing
vnoremap < <gv
vnoremap > >gv

" Ctrl-P.vim mappings
nnoremap <Leader>cf :CtrlPFunky<Cr>
nnoremap <leader>ct :CtrlPTag<cr>


let g:ctrlp_user_command = ['.git/', 'cd %s && git ls-files --exclude-standard -co']
let g:ctrlp_cache_dir = $HOME . '.cache/ctrlp'
if executable('ag')
    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*.pyc,/.venv/*

let g:ctrlp_use_caching = 1
let g:ctrlp_by_filename = 1
let g:ctrlp_show_hidden = 1
let g:ctrlp_max_height=30
let g:ctrlp_max_files = 5000
let g:ctrlp_max_depth = 100
let g:ctrlp_lazy_update = 1
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_extensions = ['funky', 'tag']

" end of line chars
set list
set listchars=tab:▸\ ,eol:¬

" save when I tab away
au FocusLost * :wa

" remap Esc
imap jk <Esc>

" moving between tabs
nnoremap <silent> <C-t> :tabnew<CR>
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" options galore
set encoding=utf-8
set expandtab
set autoindent
set softtabstop=4
set shiftwidth=4
set shiftround
set tabstop=4
set textwidth=0
set nocompatible
set nobackup
set nowritebackup
set noswapfile
set history=999
set backspace=indent,eol,start
set ruler
set showmode
set laststatus=2
set scrolloff=10
set ch=2
set hlsearch
set gdefault
set number
set hidden
set whichwrap+=<,>,[,]
set wildmenu
set title
set incsearch
set ignorecase
set ttyfast
set virtualedit=onemore
set fileencodings=.
set spelllang=en_gb
set foldmethod=indent
set foldlevel=99
set relativenumber

" fugitive.vim
nnoremap <silent> <leader>gs :Gstatus<CR>
nnoremap <silent> <leader>gd :Gdiff<CR>
nnoremap <silent> <leader>gc :Gcommit --verbose<CR>
nnoremap <silent> <leader>gam :Gcommit --verbose --amend<CR>
nnoremap <silent> <leader>gb :Gblame<CR>
nnoremap <silent> <leader>gl :Glog<CR>
nnoremap <silent> <leader>gp :Git push<CR>
nnoremap <silent> <leader>gw :Gwrite<CR>
nnoremap <silent> <leader>gbr :Git branch<CR>
nnoremap <silent> <leader>gbw :Gbrowse<CR>

" get to git via visual mode
vmap <silent> <leader>gbw :Gbrowse<CR>

" easy-motion.vim
let g:EasyMotion_leader_key = '<space>'
nmap s <Plug>(easymotion-s2)
let g:EasyMotion_smartcase = 1
let g:EasyMotion_use_upper = 1

" bubble lines
nmap <C-k> [e
nmap <C-j> ]e
vmap <C-k> [egv
vmap <C-j> ]egv

" when I close a tab, remove the buffer
set nohidden

" stop incrementing numbers by accident!
nmap <C-a> <nop>
nmap <C-x> <nop>

" close vim if last window is nerdtree *only*
let g:nerdtree_tabs_autoclose=1
let g:nerdtree_tabs_open_on_console_startup=0
let g:nerdtree_tabs_smart_startup_focus=2
let g:nerdtree_tabs_startup_cd=1

" highlight line length > than 80 chars
augroup vimrc_autocmds
    autocmd!
    autocmd FileType * highlight Excess ctermbg=DarkGrey guibg=Black
    autocmd FileType * match Excess /\%80v.*/
    autocmd FileType * set nowrap
augroup END

" syntastic file checker
let g:syntastic_python_checkers=['pylint', 'mypy']
let g:syntastic_javascript_checkers = ['jslint']
let g:syntastic_always_populate_loc_list=1
let g:syntastic_check_on_wq = 0
let g:syntastic_python_python_exec='/usr/local/bin/python3'
let g:syntastic_python_checker_args='--ignore=E501'

" syntastic :Errors
function! ToggleErrors()
    let old_last_winnr = winnr('$')
    lclose
    if old_last_winnr == winnr('$')
        " Nothing was closed, open syntastic error location panel
        Errors
    endif
endfunction
nnoremap <silent> <C-x> :<C-u>call ToggleErrors()<CR>

" close that scratch window after leaving insert mode
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" NERDtree mapping
map ,<C-n> :NERDTreeToggle<CR>

" better tmux scrolling
set mouse=a

" emmet trigger key + limit for html/css only
let g:user_emmet_leader_key='<C-f>'
autocmd FileType html,css,php EmmetInstall

" rainbow.vim
let g:rainbow_active = 1

" jedi.vim
let g:jedi#usages_command=""
let g:jedi#popup_select_first=0
let g:jedi#use_tabs_not_buffers=1
let g:jedi#show_call_signatures="2"

" supertab
let g:SuperTabDefaultCompletionType = "<c-n>"

" highlighting the current line
set cursorline

" ghc-mod
" setlocal omnifunc=necoghc#omnifunc
" let g:ycm_semantic_triggers = {'haskell' : ['.']}

" ycm
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_use_ultisnips_completer = 1
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_complete_in_comments = 1
let g:ycm_complete_in_strings = 1

" surround extra mappings
let b:surround_{char2nr("v")} = "{{ \r }}"
let b:surround_{char2nr("{")} = "{{ \r }}"
let b:surround_{char2nr("%")} = "{% \r %}"
let b:surround_{char2nr("b")} = "{% block \1block name: \1 %}\r{% endblock \1\1 %}"
let b:surround_{char2nr("i")} = "{% if \1condition: \1 %}\r{% endif %}"
let b:surround_{char2nr("w")} = "{% with \1with: \1 %}\r{% endwith %}"
let b:surround_{char2nr("f")} = "{% for \1for loop: \1 %}\r{% endfor %}"
let b:surround_{char2nr("c")} = "{% comment %}\r{% endcomment %}""}")}

" colorschemes
let g:rehash256 = 1
set background=dark
highlight Normal ctermbg=NONE
highlight nonText ctermbg=NONE
let g:solarized_termcolors=256

" python filetype tab config
autocmd FileType python set sw=4
autocmd FileType python set ts=4
autocmd FileType python set sts=4

" flake8 auto checker
autocmd BufWritePost *.py call Flake8()

" delimitMate python + ruby triple quote fix
au FileType python let b:delimitMate_nesting_quotes = ['"']

" gitgutter
let g:gitgutter_max_signs=500
let g:gitgutter_realtime=1
let g:gitgutter_highlight_lines=1

" easytags
let g:easytags_async=1
let g:easytags_events=['BufWritePost']
let g:easytags_on_cursorhold=0
let g:easytags_auto_update=0
let g:easytags_autorecurse=1
let g:easytags_python_enabled=1
