source $HOME/.zprezto/init.zsh

# editor
export EDITOR="vim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

# terminal
export TERM="xterm-256color"

# python
export PYTHONASYNCIODEBUG=1
export PYTHONDONTWRITEBYTECODE=True

# virtualenv
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
[ -e /usr/bin/virtualenvwrapper.sh ]       && source /usr/bin/virtualenvwrapper.sh
[ -e /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh
[ -e ~/.local/bin/virtualenvwrapper.sh ]   && source ~/.local/bin/virtualenvwrapper.sh

# rvm
[ -f ~/.rvm/scripts/rvm ] && source ~/.rvm/scripts/rvm

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# automatic reminders
command -v remind >/dev/null 2>&1 && remind -h ~/.reminders || {
    echo "'remind' program is not installed" >&2;
}

# pyenv
command -v pyenv >/dev/null 2>&1 && eval "$(pyenv init -)"

# aliases
source $HOME/.zsha

# functions
source $HOME/.zshf
