source ~/.zprezto/init.zsh

# still get incremental search with 'vi' keys
bindkey -M viins '^r' history-incremental-search-backward
bindkey -M vicmd '^r' history-incremental-search-backward

# get bash style comments
setopt interactivecomments

# zsh plugins
# https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zpreztorc#L25
zstyle ':prezto:load' pmodule \
  'directory' \
  'utility' \
  'completion' \
  'git' \
  'prompt' \
  'syntax-highlighting' \
  'history-substring-search' \

# dotfiles
[ -f ~/.zsha ] && source ~/.zsha
[ -f ~/.zshf ] && source ~/.zshf
[ -f ~/.zpreztorc ] && source ~/.zpreztorc

# autoenv
[ -f ~/.autoenv/activate.sh ] && source ~/.autoenv/activate.sh

# autoenv
[ -f ~/.rvm/scripts/rvm ] && source ~/.rvm/scripts/rvm

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# remind
command -v remind >/dev/null 2>&1 && remind -h ~/.reminders

# nvm
[ -f "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# git/hub auto complete
setopt complete_aliases
