#!/usr/bin/env bash

DOTDIR="$HOME/dotfiles/dotfiles"

mkdir -p ${XDG_CONFIG_HOME:=$HOME/.irssi}
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
cd $DOTDIR

# delete all dotfiles present, suppress stderr
for f in *; do
  if [[ $f = "config" ]] ; then rm ~/.irssi/$f 2> /dev/null; fi
  if [[ $f = "init.vim" ]] ; then rm ~/.config/nvim/$f 2> /dev/null; fi
  rm ~/.$f 2> /dev/null;
done

# symlink all dotfiles
for f in *; do
  if [[ $f = "config" ]] ;
  then
    # put `config` in `~/.irssi/config
    ln -s $(realpath ./$f) ~/.irssi/$f
    file ~/.irssi/$f
  elif [[ $f = "init.vim" ]] ;
  then
    # put `init.vim` in ~/.config/nvim/init.vim
    ln -s $(realpath ./$f) ~/.config/nvim/$f
    file ~/.config/nvim/$f
  else
    # stick everything else in ~/ as a dotfile
    ln -s $(realpath ./$f) ~/.$f
    file ~/.$f
  fi
done
