# oh-my-zsh config
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="lambda"
source $ZSH/oh-my-zsh.sh

# oh-my-zsh plugins
plugins=(git vi-mode stack python autoenv)

# dotfiles
source ~/.zsha
source ~/.zshf

# zsh bindings
bindkey -M viins '^r' history-incremental-search-backward
bindkey -M vicmd '^r' history-incremental-search-backward
bindkey -M viins 'jk' vi-cmd-mode

# path exports
PATH+=$PATH

RVM_DIR=$HOME/.rvm/bin
if [ -d "$RVM_DIR" ]; then PATH+=:$RVM_DIR; fi

RVM_DIR2=$HOME/.rvm/gems/ruby-*/bin/*
if [ -d "$RVM_DIR2" ]; then PATH+=:$RVM_DIR2; fi

PYENV_ROOT=$HOME/.pyenv
if [ -d "$PYENV_ROOT" ]; then PATH+=$PYENV_ROOT; fi

PATH+=:$HOME/.local/bin
PATH+=:$HOME/bin
export PATH

# editor
export EDITOR="nvim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

# tmux exports
[[ $TMUX = "" ]] && export TERM="xterm-256color"

# python exports
export PYTHONASYNCIODEBUG=1
export PYTHONDONTWRITEBYTECODE=True

# fzf exports
export FZF_COMPLETION_TRIGGER='X'
export FZF_DEFAULT_OPTS='--black --no-256 --no-color'

# pyenv exports
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_VERSION='3.5.2'
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# programs
[ -f ~/.rvm/scripts/rvm ] && source ~/.rvm/scripts/rvm
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# reminders
command -v remind >/dev/null 2>&1 && remind -h ~/.reminders

# autoenv
source ~/.autoenv/activate.sh
