PATH+="$PATH"
PATH+=:"$HOME/.nvm"
PATH+=:"$HOME/.local/bin"
PATH+=:"$HOME/bin"
export PATH

export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="lambda"
export EDITOR="nvim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR
export PYTHONASYNCIODEBUG=1
export PYTHONDONTWRITEBYTECODE=True
export FZF_COMPLETION_TRIGGER='X'
export FZF_DEFAULT_OPTS='--black --no-256 --no-color'
export $(gnome-keyring-daemon -s)
export DISABLE_AUTO_TITLE="true"
export NVM_DIR="$HOME/.nvm"
export ZSH_AUTOSUGGEST_USE_ASYNC=true

source ~/.zsha
source ~/.zshf
source ~/.fzf.zsh
source $ZSH/oh-my-zsh.sh
source ~/.autoenv/activate.sh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

[[ $TMUX = "" ]] && export TERM="xterm-256color"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

plugins=(git vi-mode stack python autoenv)

bindkey -v
bindkey -M viins '^r' history-incremental-search-backward
bindkey -M vicmd '^r' history-incremental-search-backward
bindkey -M viins 'jk' vi-cmd-mode
bindkey '^L' autosuggest-accept

remind -h ~/remind/reminders.txt
