#!/bin/bash

# Backup the important stuff with Borg

borg create ::ssh-$(date --iso-8601=date) ~/.ssh
borg create ::gpg-$(date --iso-8601=date) ~/.gnupg
borg create ::pass-$(date --iso-8601=date) ~/.password-store
borg create ::docs-$(date --iso-8601=date) ~/docs
borg create ::aliases-$(date --iso-8601=date) ~/.mutt/aliases
borg create ::notes-$(date --iso-8601=date) ~/notes
borg create ::aptivate-$(date --iso-8601=date) ~/aptivate/vpn

borg prune --keep-within 1d
